-- DROP TABLE CATEGORY;

CREATE 	TABLE CATEGORY (CATEGORY_ID INT(11) NOT NULL AUTO_INCREMENT, 
						CATEGORY_NAME VARCHAR(45) NOT NULL, 
                        PRIMARY KEY (CATEGORY_ID));
                        
SELECT * FROM CATEGORY;

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'APPAREL');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'WESTERN');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'ETHINIC');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, 'INDIAN');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, 'INDIAN');


SHOW VARIABLES WHERE VARIABLE_NAME = 'PORT';
SELECT DATABASE();

Select CATEGORY_ID, CATEGORY_NAME from category;

SELECT * FROM CATEGORY WHERE CATEGORY_ID = 3 AND CATEGORY_NAME = "ETHINIC";

SELECT * FROM CATEGORY WHERE CATEGORY_ID = 4;